### ISSUE TITLE
The following result did not validate with schema: #/definitions/QuoteSummaryResult

### ISSUE THREAD

**Issue by goshik123** [gadicc/node-yahoo-finance2#501] opened 2022-06-29 18:16 UTC
# Bug Report
The following result did not validate with schema: #/definitions/QuoteSummaryResult
[
  {
    instancePath: '/summaryDetail',
    schemaPath: '#/definitions/SummaryDetail/additionalProperties',
    keyword: 'additionalProperties',
    params: { additionalProperty: 'coinMarketCapLink' },
    message: 'must NOT have additional properties',
    data: {
      maxAge: 1,
      priceHint: 2,
      previousClose: 15.02,
      open: 15.19,
## Describe the bug
This issue is happening with All Symbols.    Probably something changed in Yahoo interface

**Comment by goshik123** [comment] 2022-06-29 18:17
Please check.   It worked fine. The issue  is with "SummaryDetail"  portion. 

Thanks
Igor

**Comment by gadicc** [comment] 2022-06-29 20:27
Hey @goshik123, I can't reproduce this with any symbol.  It looks like exactly what I fixed earlier.  Are you definitely using the new version I released in your last issue?  What is the output of `npm ls yahoo-finance2` and can you give an example of any symbol this is still happening with.  Thanks.

**Comment by gadicc** [comment] 2022-06-29 20:59
That's one way, but you'll lose all the validation.  Try v2.3.4 :)  A lot has happened since v2.1.0.

**Comment by goshik123** [comment] 2022-06-29 21:00
How can I update my version?

**Comment by gadicc** [comment] 2022-06-29 21:01
Depending on your package manager:

* `npm i yahoo-finance2@latest`
* `yarn add yahoo-finance2@latest`

or `@2.3.4`, but `@latest` will always get the latest release.  Same for any npm package.

**Comment by goshik123** [comment] 2022-06-29 21:10
Great. Thank you. All is working without  ,{validateResult: false} ...

Thank you again :)

**Closed** 2022-06-29 21:11 UTC
Labels: bug
