### ISSUE TITLE
Failed validation: #/definitions/QuoteSummaryResult

### ISSUE THREAD

**Issue by bmacedo** [gadicc/node-yahoo-finance2#656] opened 2023-07-15 22:05 UTC
# Validation Error

## Symbol(s) that it happened for
- CSH2.L

## Error Message

```
The following result did not validate with schema: #/definitions/QuoteSummaryResult
[
  {
    "instancePath": "/topHoldings",
    "schemaPath": "#/required",
    "keyword": "required",
    "params": {
      "missingProperty": "stockPosition"
    },
    "message": "must have required property 'stockPosition'",
    "data": {
      "maxAge": 1,
      "holdings": [],
      "equityHoldings": {
        "priceToEarnings": 0,
        "priceToBook": 0,
        "priceToSales": 0,
        "priceToCashflow": 0
      },
      "bondHoldings": {},
      "bondRatings": [],
      "sectorWeightings": []
    }
  },
  {
    "instancePath": "/topHoldings",
    "schemaPath": "#/required",
    "keyword": "required",
    "params": {
      "missingProperty": "bondPosition"
    },
    "message": "must have required property 'bondPosition'",
    "data": {
      "maxAge": 1,
      "holdings": [],
      "equityHoldings": {
        "priceToEarnings": 0,
        "priceToBook": 0,
        "priceToSales": 0,
        "priceToCashflow": 0
      },
      "bondHoldings": {},
      "bondRatings": [],
      "sectorWeightings": []
    }
  }
]
```

## Environment
Browser or Node: node
Node version (if applicable): 
Npm version: 
Browser verion (if applicable):
Library version (e.g. `1.10.1`): yahoo-finance2 v2.4.2

## Additional Context
Issue reproducible when importing transactions on [ghostfolio](https://github.com/ghostfolio/ghostfolio#self-hosting) with this particular ticker

**Comment by dtslvr** [comment] 2023-07-23 14:25
This looks like a duplicate of #639.

**Comment by gadicc** [comment] 2023-07-24 08:45
Right you are, thanks, @dtslvr.

And thanks @bmacedo for reporting.

Fixed in the original issue above.

**Closed by gadicc** 2023-07-24 08:45 UTC
Labels: bug, duplicate, validation
