### ISSUE TITLE
doesn't import as described

### ISSUE THREAD

**Issue by CFautt** [gadicc/node-yahoo-finance2#143] opened 2021-04-22 03:09 UTC
# Bug Report

## Describe the bug

importing as described in docs results in the following error:

(node:67008) UnhandledPromiseRejectionWarning: TypeError: yahooFinance.quote is not a function.

## Minimal Reproduction
`var yahooFinance = require('yahoo-finance2');
yahooFinance.quote('AAPL')`

## Environment
Browser or Node: node
Node version (if applicable): 14.6.0
Npm version: 6.14.11
Browser verion (if applicable):
Library version (e.g. `1.10.1`): 

## Additional Context
I got it to work with `var yahooFinance = require('yahoo-finance2').default` but it just feels wrong.

**Comment by gadicc** [comment] 2021-04-22 06:06
Hey @CFautt, thanks for reporting.

Yes, it looks like when `require()`-ing vs `import`-ing you need to do this.  I guess when #126 lands that won't be necessary anymore.

Can you just let us know where you saw `require` in the docs?  As we should really only be showing examples with `import`.  (If you're using Babel, TypeScript, etc, it's transpiled down to a `require` statement that checks for modules and automatically returns the `.default` prop in this case).

When #126 lands I'll make sure to add examples in the README for both and make sure that both forms work well (i.e. no need to ref `.default` in CommonJS.

Thanks!

**Comment by CFautt** [comment] 2021-04-22 13:23
Thanks for responding so quickly @gadicc! 
You're right that require is nowhere in the docs, so that's unfair to expect to work. I get the same error when I try importing it like this, though:

`import yahooFinance from 'yahoo-finance2';
var test = async function(){
    const results = await yahooFinance.quote('AAPL');
    console.log(results);
}`

and need to amend the call of the function to `const results = await yahooFinance.default.quote('AAPL');` to make it work.

Thank you for all your work on this project!

**Comment by gadicc** [comment] 2021-04-22 14:37
Hey @CFautt, thanks for reporting back, and for your kind words.

That is indeed surprising.  What is your setup?   Bundlers / transpilers / etc?

I just noticed that in a plain node project, with `{ "type": "module" }` in the `package.json`, you'll experience this.  Is that your use case?  If that's the case, #126 (when it lands) will indeed fix this.

**Comment by CFautt** [comment] 2021-04-22 15:58
That is exactly my setup, so it seems it will be fixed soon!

**Comment by gadicc** [comment] 2021-05-08 08:46
@CFautt, #126 / #144 is merged to the devel branch.  Not released yet but in case you're comfortable with running development versions from github, you could check it out.  Otherwise you'll see an automated message here once it's released as a package to npm.

* Pure/true ESM module that works great with `import` in a `{ "type": "module" }` project
* Note in README about the modules (this you can see already)
* Clear instructions in the above to use `require().default` for a pure CommonJS project
* Interop projects (ESM implemented in CJS, by e.g. Babel) work as expected.

**Comment by gadicc** [comment] 2021-06-01 05:23
Hey @CFautt, as above, and now released in v1.11.0.  Let us know how you go with that.  If you're using `import`, you can drop the `.default` from your work now (but it's still required for `require`, as explained in the docs).

**Comment by gadicc** [comment] 2021-06-01 05:23
Actually maybe you can report back before we close this issue.  Thanks :)

**Comment by PythonCreator27** [comment] 2021-06-04 16:54
@gadicc I can confirm that this is fixed with the latest version.

**Comment by gadicc** [comment] 2021-06-05 07:34
Awesome, @PythonCreator27, thanks for confirming! :pray:

**Closed by gadicc** 2021-06-05 07:34 UTC
Labels: bug
