### ISSUE TITLE
search quotesCount works only up to 5

### ISSUE THREAD

**Issue by vrobik** [gadicc/node-yahoo-finance2#607] opened 2023-02-24 19:05 UTC
# Bug Report
module search -> queryOptions -> quotesCount works only up to 5 
is this limit from the yahoo side?

## Describe the bug
quotes always have 2 elements with "isYahooFinance": false, and other with true but only up to 5 even if I set this limit to 10

## Minimal Reproduction
```javascript
const symbols = await yahooFinance.search('a', {quotesCount: 1, newsCount: 1});
console.log('symbols.quotes:', symbols.quotes.length); //symbols.quotes: 3
console.log('symbols.news:', symbols.news.length); //symbols.news: 1

const symbols = await yahooFinance.search('a', {quotesCount: 10, newsCount: 10});
console.log('symbols.quotes:', symbols.quotes.length); //symbols.quotes: 7
console.log('symbols.news:', symbols.news.length); //symbols.news: 10
```

## Environment
Browser or Node: 
Node version (if applicable): 16.16.0
Npm version: 8.11.0
Browser verion (if applicable):
Library version: "yahoo-finance2": "^2.3.10"

**Comment by Benjythebee** [comment] 2023-07-22 03:45
Can confirm. Just faced this today

**Comment by gadicc** [comment] 2023-08-12 10:46
Hey @vrobik and @Benjythebee, thanks for the reports and your patience.

Indeed seems to be an issue on the Yahoo side... we pass on these keys directly to Yahoo, and don't touch them or limit the results in any other way; so I guess Yahoo have some hardcoded limits their side to limit compute.

Closing for now but please feel free to re-open if you figure out anything more about this!  And thanks for the easy reproductions, @vrobik.

**Closed by gadicc** 2023-08-12 10:46 UTC
Labels: bug
