### ISSUE TITLE
Failed validation: #/definitions/QuoteResponseArray

### ISSUE THREAD

**Issue by timothykou** [gadicc/node-yahoo-finance2#354] opened 2021-12-09 22:03 UTC
# Validation Error

## Symbol(s) that it happened for
- BKR
- GRMN

## Error Message

```
 {
    instancePath: '/341/quoteType',
    schemaPath: '#/definitions/QuoteIndex/properties/quoteType/const',
    keyword: 'const',
    params: { allowedValue: 'INDEX' },
    message: 'must be equal to constant',
    data: 'EQUITY'
  },
  {
    instancePath: '/341',
    schemaPath: '#/definitions/QuoteMutualfund/additionalProperties',
    keyword: 'additionalProperties',
    params: { additionalProperty: 'prevExchange' },
    message: 'must NOT have additional properties',
    data: {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      quoteSourceName: 'Nasdaq Real Time Price',
      ...
      shortName: 'Garmin Ltd.',
      displayName: 'Garmin',
      symbol: 'GRMN'
    }
  },
...

```

## Environment
Browser or Node: Node
Node version (if applicable): 12.21.0
Npm version: 
Browser verion (if applicable):
Library version (e.g. `1.10.1`): yahoo-finance2@1.14.7

## Additional Context
The following edit to the provided code sandbox (with any combination of a symbol and either `BKR` and/or `GRMN`) will return the below error:

```
import yahooFinance from "yahoo-finance2";
import { show } from "./utils";

show(async () => {
  const result = await yahooFinance.quote(["BKR", "TSLA"])

  // 2. Put a "." after result to explore
  return result;

  // 3. Try change "quoteSummary" above to something else
});
```
```
{
  "name": "FailedYahooValidationError",
  "message": "Failed Yahoo Schema validation"
}
```

**Comment by glaucoheitor** [comment] 2021-12-28 09:40
I did a few tests and wasn't able to reproduce your errors, I tries different versions of Node and this library.

Can you provide other examples of your code where this error happens?

**Comment by gadicc** [comment] 2021-12-28 09:44
hey @glaucoheitor, thanks for your input on this, and thanks @timothykou for your patience.  I meant to say earlier, that, I was also not able to reproduce.  I thought maybe it could have been time-dependent so I had been trying at different times (the Yahoo response can vary by trading period (closed, pre-market, etc) but still haven't come across it yet.

I was tempted to cover this case regardless but I'd really rather have real input to test against, understand in which cases it comes up, or if it was something Yahoo added temporarily and then removed after.  If you or anyone else has any further input, I'll be happy to hear it.  Thanks!

**Comment by ayyagari-dalalstreet** [comment] 2022-02-23 21:41
I am also facing the similar issue due to which there is a large data set being rendered directly to the logs with changes in the mapping from the response objects.

**Comment by gadicc** [comment] 2022-02-24 08:54
Thanks @ayyagari-dalalstreet I believe however this might be a different issue, a new property Yahoo introduced I think yesterday... tracking in #412.

**Comment by gadicc** [comment] 2022-03-06 16:20
Closing, since I wasn't able to reproduce.  Yahoo occasionally add fields and change their mind suddenly and remove them soon after :sweat:   In any case, since #411, these kind of surprises won't throw errors anymore.

**Closed by gadicc** 2022-03-06 16:20 UTC
Labels: bug, validation
